/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     2012/9/18 16:36:11                           */
/*==============================================================*/


DROP PROCEDURE IF EXISTS FDE_PROCESS_DELETE/*#*/;

DROP PROCEDURE IF EXISTS FDE_PROCESS_DELETE_DEADPROCESS/*#*/;

DROP PROCEDURE IF EXISTS FDE_PROCESS_INSERT/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_CHECK_LOCK_CONFLICTS/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_LOCK/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_LOCK_DELETE/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_LOCK_DELETE_USER/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_LOCK_INSERT/*#*/;

DROP PROCEDURE IF EXISTS FDE_TABLE_LOCK_UPDATE/*#*/;

DROP PROCEDURE IF EXISTS FDE_OBJECT_LOCK/*#*/;

DROP PROCEDURE IF EXISTS FDE_OBJECT_LOCK_DELETE/*#*/;

DROP TABLE IF EXISTS FDB_GRIDINDEX/*#*/;

DROP TABLE IF EXISTS FDB_GEOCOLUMN/*#*/;

DROP TABLE IF EXISTS FDB_RENDERINDEX/*#*/;

DROP TABLE IF EXISTS FDB_COLUMN_REGISTRY/*#*/;

DROP TABLE IF EXISTS FDB_TABLE_REGISTRY/*#*/;

DROP TABLE IF EXISTS FDE_TABLE_LOCKS/*#*/;

DROP TABLE IF EXISTS FDE_OBJECT_LOCKS/*#*/;

DROP TABLE IF EXISTS FDB_OBJECTCLASSES/*#*/;

DROP TABLE IF EXISTS FDB_FEATUREDATASET/*#*/;

DROP TABLE IF EXISTS FDB_ITEMS/*#*/;

DROP TABLE IF EXISTS FDB_ITEMTYPES/*#*/;

DROP TABLE IF EXISTS FDB_REPLICATION_STEP/*#*/;

DROP TABLE IF EXISTS FDB_SERVERCONFIG/*#*/;

DROP TABLE IF EXISTS FDB_SERVERINFO/*#*/;

DROP TABLE IF EXISTS FDE_CONNECTIONINFO/*#*/;

DROP TABLE IF EXISTS FDE_PROCESS_INFORMATION/*#*/;

DROP TABLE IF EXISTS FDE_REP_CHECKOUTINFO/*#*/;

DROP TABLE IF EXISTS FDE_REP_FULLREPLICATIONTABLE/*#*/;

DROP TABLE IF EXISTS FDE_REP_TABLE_MODIFIED/*#*/;

DROP TABLE IF EXISTS FDE_SPATIAL_REFERENCES/*#*/;

/*==============================================================*/
/* Table: FDB_FEATUREDATASET                                    */
/*==============================================================*/
CREATE TABLE FDB_FEATUREDATASET
(
   DATASETID            INT NOT NULL AUTO_INCREMENT,
   DATASETNAME          VARCHAR(128) NOT NULL,
   DATASETALIASNAME     VARCHAR(255),
   DATASETUUID          VARCHAR(40) NOT NULL,
   DATABASENAME         VARCHAR(32),
   SCHEMANAME           VARCHAR(32),
   DESCRIPTION          VARCHAR(1024),
   SRID                 INT NOT NULL,
   TRID                 INT NOT NULL,
   REGISTEROPTION       INT NOT NULL DEFAULT 0,
   EDITVERSION          INT NOT NULL DEFAULT 0,
   CREATETIME           DATETIME NOT NULL,
   LASTUPDATETIME       DATETIME NOT NULL,
   PRIMARY KEY (DATASETID),
   UNIQUE KEY AK_UK_DTNAME_DBNAME (DATASETNAME, DATABASENAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_OBJECTCLASSES                                     */
/*==============================================================*/
CREATE TABLE FDB_OBJECTCLASSES
(
   CLASSID              INT NOT NULL AUTO_INCREMENT,
   DATASETID            INT NOT NULL,
   DATABASENAME         VARCHAR(32) NOT NULL,
   SCHEMANAME           VARCHAR(32) NOT NULL,
   CLASSNAME            VARCHAR(128) NOT NULL,
   ALIASNAME            VARCHAR(255),
   CLSUUID              VARCHAR(40) NOT NULL,
   OIDCOLUMN            VARCHAR(32) NOT NULL,
   CLASSTYPE            INT NOT NULL,
   DESCRIPTION          VARCHAR(1024),
   CREATETIME           DATETIME NOT NULL,
   LASTUPDATETIME       DATETIME NOT NULL,
   REGISTEROPTION       INT NOT NULL DEFAULT 0,
   PRIMARY KEY (CLASSID),
   KEY AK_UK_TNAME_DBNAME (DATABASENAME, CLASSNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_COLUMN_REGISTRY                                   */
/*==============================================================*/
CREATE TABLE FDB_COLUMN_REGISTRY
(
   COLUMNID             INT NOT NULL AUTO_INCREMENT,
   DOMAINID             INT,
   CLASSID              INT NOT NULL,
   FIELDNAME            VARCHAR(255) NOT NULL,
   ALIASNAME            VARCHAR(255),
   DEFAULTVALUESTRING   VARCHAR(255),
   DEFAULTVALUENUMBER   NUMERIC(38,8),
   ISNULLABLE           INT NOT NULL,
   ISEDITABLE           INT NOT NULL,
   ISREQUIRED           INT,
   ISSYSTEMCOLUMN       INT,
   ISRANDERINDEXFIELD   INT NOT NULL DEFAULT 0,
   FDE_TYPE             INT NOT NULL,
   COLUMN_SIZE          INT NOT NULL,
   DECIMAL_DIGITS       INT NOT NULL,
   PRIMARY KEY (COLUMNID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_GEOCOLUMN                                         */
/*==============================================================*/
CREATE TABLE FDB_GEOCOLUMN
(
   COLUMNID             INT NOT NULL,
   F_TABLENAME          VARCHAR(64) NOT NULL,
   AVGPOINTCNT          INT NOT NULL,
   GEOTYPE              INT NOT NULL,
   HASID                INT NOT NULL,
   HASM                 INT NOT NULL,
   HASZ                 INT NOT NULL,
   STORAGETYPE          INT NOT NULL,
   MAXX                 DOUBLE NOT NULL,
   MAXY                 DOUBLE NOT NULL,
   MAXZ                 DOUBLE NOT NULL,
   MAXM                 DOUBLE NOT NULL,
   MINX                 DOUBLE NOT NULL,
   MINY                 DOUBLE NOT NULL,
   MINZ                 DOUBLE NOT NULL,
   MINM                 DOUBLE NOT NULL,
   PRIMARY KEY (COLUMNID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_GRIDINDEX                                         */
/*==============================================================*/
CREATE TABLE FDB_GRIDINDEX
(
   COLUMNID             INT NOT NULL,
   S_TABLENAME          VARCHAR(64) NOT NULL,
   INDEXNAME            VARCHAR(255) NOT NULL,
   CENTERX              DOUBLE NOT NULL,
   CENTERY              DOUBLE NOT NULL,
   L1                   DOUBLE NOT NULL,
   L2                   DOUBLE NOT NULL,
   L3                   DOUBLE NOT NULL,
   RADIO                DOUBLE NOT NULL,
   PRIMARY KEY (COLUMNID),
   KEY AK_UC_FDB_GRIDINDEX_NAME (INDEXNAME),
   KEY AK_UC_FDB_GRIDINDEX_STNAME (S_TABLENAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_ITEMS                                             */
/*==============================================================*/
CREATE TABLE FDB_ITEMS
(
   ID                   INT NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(128) NOT NULL,
   FULLNAME             VARCHAR(255) NOT NULL,
   GUID                 VARCHAR(40) NOT NULL,
   TYPE                 VARCHAR(40) NOT NULL,
   BASETYPE             VARCHAR(40) NOT NULL,
   DEFAULTS             LONGBLOB,
   DEFINITION           LONGBLOB,
   DOCUMENTATION        LONGBLOB,
   PRIMARY KEY (ID),
   UNIQUE KEY UK_FDB_ITEMS (FULLNAME,BASETYPE)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_ITEMTYPES                                         */
/*==============================================================*/
CREATE TABLE FDB_ITEMTYPES
(
   ID                   INT NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(255) NOT NULL,
   GUID                 VARCHAR(40) NOT NULL,
   PARENTTYPEGUID       VARCHAR(40) NOT NULL,
   PRIMARY KEY (ID),
   KEY AK_IDENTIFIER_2 (NAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_RENDERINDEX                                       */
/*==============================================================*/
CREATE TABLE FDB_RENDERINDEX
(
   COLUMNID             INT NOT NULL,
   INDEXNAME            VARCHAR(255) NOT NULL,
   CENTERX              DOUBLE NOT NULL,
   CENTERY              DOUBLE NOT NULL,
   L1                   DOUBLE NOT NULL,
   L2                   DOUBLE NOT NULL,
   L3                   DOUBLE NOT NULL,
   RADIO                DOUBLE NOT NULL,
   FB_TABLENAME			VARCHAR(255) NOT NULL,
   PRIMARY KEY (COLUMNID),
   KEY AK_FDB_RENDERINDEX_UC_NAME (INDEXNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_REPLICATION_STEP                                  */
/*==============================================================*/
CREATE TABLE FDB_REPLICATION_STEP
(
   ID                   INT NOT NULL AUTO_INCREMENT,
   DATASETID            INT NOT NULL,
   OPTYPE               INT NOT NULL,
   STEP                 INT NOT NULL,
   SUBSTEP              INT DEFAULT 0,
   DESCRIPTION          VARCHAR(1024),
   ISDONE               INT NOT NULL,
   DATA                 TEXT,
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_SERVERCONFIG                                      */
/*==============================================================*/
CREATE TABLE FDB_SERVERCONFIG
(
   PARAMETERNAME        VARCHAR(128) NOT NULL,
   PARAMETERVALUE       VARCHAR(255) NOT NULL,
   PRIMARY KEY (PARAMETERNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_SERVERINFO                                        */
/*==============================================================*/
CREATE TABLE FDB_SERVERINFO
(
   DATABASENAME         VARCHAR(255),
   INSTANCENAME         VARCHAR(255),
   USERNAME             VARCHAR(255) NOT NULL,
   CREATETIME           TIMESTAMP NOT NULL,
   FDBVERSIONMAJOR      INT NOT NULL,
   FDBVERSIONMINOR      INT NOT NULL,
   FDBVERSIONBUGFIX     INT NOT NULL,
   FDEPROVIDERNAME      VARCHAR(255) NOT NULL,
   FDEDESCRIPTION       VARCHAR(1024),
   UID                  VARCHAR(64) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDB_TABLE_REGISTRY                                    */
/*==============================================================*/
CREATE TABLE FDB_TABLE_REGISTRY
(
   TABLEREGISTRATION_ID INT NOT NULL AUTO_INCREMENT,
   CLASSID              INT,
   DATABASENAME         VARCHAR(32) NOT NULL,
   SCHEMANAME           VARCHAR(32) NOT NULL,
   TABLENAME            VARCHAR(32) NOT NULL,
   TABLETYPE            INT NOT NULL,
   ISSYSTEMTABLE        INT NOT NULL,
   DESCRIPTION          VARCHAR(1024),
   REGISTRATIONDATE     DATETIME NOT NULL,
   LASTUPDATETIME       DATETIME NOT NULL,
   PRIMARY KEY (TABLEREGISTRATION_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_CONNECTIONINFO                                    */
/*==============================================================*/
CREATE TABLE FDE_CONNECTIONINFO
(
   CONNECTID            INTEGER NOT NULL,
   HOST                 VARCHAR(128) NOT NULL,
   USERNAME             VARCHAR(32) NOT NULL,
   FDEID                INTEGER,
   PRIMARY KEY (CONNECTID, HOST, USERNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_PROCESS_INFORMATION                               */
/*==============================================================*/
CREATE TABLE FDE_PROCESS_INFORMATION
(
   FDEID                INT NOT NULL AUTO_INCREMENT,
   SPID                 INT NOT NULL,
   PID                  INT NOT NULL,
   STARTTIME            DATETIME NOT NULL,
   OWNER                VARCHAR(32) NOT NULL,
   DIRECTCONNECT        CHAR(1) NOT NULL,
   PRIMARY KEY (FDEID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_REP_CHECKOUTINFO                                  */
/*==============================================================*/
CREATE TABLE FDE_REP_CHECKOUTINFO
(
   ID                   INT NOT NULL AUTO_INCREMENT,
   DATASETID            INT,
   CHECKOUTNAME         VARCHAR(40) NOT NULL,
   CHECKOUTDATETIME     DATETIME NOT NULL,
   BCHECKOUT            INT NOT NULL,
   BMASTER              INT NOT NULL DEFAULT 0,
   CONN                 VARCHAR(1024),
   PRIMARY KEY (ID),
   UNIQUE KEY AK_CHECKOUTNAME (CHECKOUTNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_REP_FULLREPLICATIONTABLE                          */
/*==============================================================*/
CREATE TABLE FDE_REP_FULLREPLICATIONTABLE
(
   ID                   INT NOT NULL AUTO_INCREMENT,
   REGISTERCLASSID      INT NOT NULL,
   DATASETID            INT NOT NULL,
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_REP_TABLE_MODIFIED                                */
/*==============================================================*/
CREATE TABLE FDE_REP_TABLE_MODIFIED
(
   ID                   INT NOT NULL,
   TABLEREGISTERID      INT NOT NULL,
   FIELDID              INT NOT NULL,
   OPTYPE               INT NOT NULL,
   BKEEP                INT NOT NULL COMMENT '这个字段用在同时冲突解决时，在从端有用。
            -1表示未进行过冲突检测
            0表示放弃从端，以主端为主
            1表示保留从端，放弃主端更改',
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_SPATIAL_REFERENCES                                */
/*==============================================================*/
CREATE TABLE FDE_SPATIAL_REFERENCES
(
   SRID                 INT NOT NULL AUTO_INCREMENT,
   DESCRIPTION          VARCHAR(1024),
   AUTH_NAME            VARCHAR(255),
   AUTH_SRID            INT,
   FALSEX               DOUBLE NOT NULL,
   FALSEY               DOUBLE NOT NULL,
   XYUNITS              DOUBLE NOT NULL,
   FALSEZ               DOUBLE NOT NULL,
   ZUNITS               DOUBLE NOT NULL,
   FALSEM               DOUBLE NOT NULL,
   MUNITS               DOUBLE NOT NULL,
   XYCLUSTER_TOL        DOUBLE,
   ZCLUSTER_TOL         DOUBLE,
   MCLUSTER_TOL         DOUBLE,
   SRTEXT               VARCHAR(1024) NOT NULL,
   PRIMARY KEY (SRID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_TABLE_LOCKS                                       */
/*==============================================================*/
CREATE TABLE FDE_TABLE_LOCKS
(
   FDEID                INT NOT NULL,
   LOCKTYPE             CHAR(1) NOT NULL,
   CLASSID              INT NOT NULL,
   PRIMARY KEY (FDEID, LOCKTYPE, CLASSID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

/*==============================================================*/
/* Table: FDE_OBJECT_LOCKS                                       */
/*==============================================================*/
CREATE TABLE FDE_OBJECT_LOCKS
(
   FDEID                INT NOT NULL,
   LOCKTYPE             CHAR(1) NOT NULL DEFAULT 'E',
   CLASSID              INT NOT NULL,
   OBJECTID             INT NOT NULL,
   PRIMARY KEY (FDEID, LOCKTYPE, CLASSID,OBJECTID),
   UNIQUE KEY UK_FDE_OBJECT_LOCKS (CLASSID,OBJECTID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8/*#*/;

ALTER TABLE FDB_COLUMN_REGISTRY ADD CONSTRAINT FK_RELATIONSHIP_16 FOREIGN KEY (DOMAINID)
      REFERENCES FDB_ITEMS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT/*#*/;

ALTER TABLE FDB_COLUMN_REGISTRY ADD CONSTRAINT FK_TABLECOLUMNLINK FOREIGN KEY (CLASSID)
      REFERENCES FDB_OBJECTCLASSES (CLASSID)/*#*/;

ALTER TABLE FDB_GEOCOLUMN ADD CONSTRAINT FK_FDB_GEOCOLUMN FOREIGN KEY (COLUMNID)
      REFERENCES FDB_COLUMN_REGISTRY (COLUMNID) ON DELETE CASCADE/*#*/;

ALTER TABLE FDB_GRIDINDEX ADD CONSTRAINT FK_GEOCOLUMNGRIDINDEXLINK FOREIGN KEY (COLUMNID)
      REFERENCES FDB_COLUMN_REGISTRY (COLUMNID)/*#*/;

ALTER TABLE FDB_OBJECTCLASSES ADD CONSTRAINT FK_FEATUREDATASETCLASSLINK FOREIGN KEY (DATASETID)
      REFERENCES FDB_FEATUREDATASET (DATASETID)/*#*/;

ALTER TABLE FDB_RENDERINDEX ADD CONSTRAINT FK_COLUMN_RENDERINDEX_PK_LINK FOREIGN KEY (COLUMNID)
      REFERENCES FDB_COLUMN_REGISTRY (COLUMNID) ON DELETE CASCADE ON UPDATE CASCADE/*#*/;

ALTER TABLE FDB_TABLE_REGISTRY ADD CONSTRAINT FK_OBJECTATTACHLINK FOREIGN KEY (CLASSID)
      REFERENCES FDB_OBJECTCLASSES (CLASSID)/*#*/;

ALTER TABLE FDE_REP_CHECKOUTINFO ADD CONSTRAINT FK_CHECKOUTDATASETLINK FOREIGN KEY (DATASETID)
      REFERENCES FDB_FEATUREDATASET (DATASETID)/*#*/;

ALTER TABLE FDE_TABLE_LOCKS ADD CONSTRAINT FK_FDE_PROCESSINFO_TABLELOCKS FOREIGN KEY (FDEID)
      REFERENCES FDE_PROCESS_INFORMATION (FDEID)/*#*/;

ALTER TABLE FDE_TABLE_LOCKS ADD CONSTRAINT FK_TABLETABLELOCKLINK FOREIGN KEY (CLASSID)
      REFERENCES FDB_OBJECTCLASSES (CLASSID)/*#*/;

ALTER TABLE FDE_OBJECT_LOCKS ADD CONSTRAINT FK_OBJECT_LOCK_PK_LINK FOREIGN KEY (CLASSID)
      REFERENCES FDB_OBJECTCLASSES (CLASSID) ON DELETE CASCADE/*#*/;
DELIMITER $$

/**删除指定的连接进程，删除内容包括该连接进程相关的表锁，连接信息，进程信息*/
CREATE PROCEDURE FDE_PROCESS_DELETE(IN F_ID INT,IN CONN_ID INT)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE BSUCCESS INT DEFAULT 1;
	DECLARE F_ID2 INT DEFAULT 0;
	DECLARE CUR CURSOR FOR SELECT FDEID FROM FDE_CONNECTIONINFO WHERE CONNECTID=CONN_ID AND FDEID= F_ID;
	DECLARE CONTINUE HANDLER FOR  SQLEXCEPTION   SET BSUCCESS = 0;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	START TRANSACTION;
		IF CONN_ID = 0 THEN
			DELETE FROM FDE_TABLE_LOCKS WHERE FDEID= F_ID;
			DELETE FROM FDE_OBJECT_LOCKS WHERE FDEID= F_ID;	
			DELETE FROM FDE_CONNECTIONINFO WHERE FDEID= F_ID;
			DELETE FROM FDE_PROCESS_INFORMATION WHERE FDEID= F_ID;
		ELSE
			OPEN  CUR;
			REPEAT
				FETCH CUR INTO F_ID2;
				IF NOT DONE THEN
					DELETE FROM FDE_TABLE_LOCKS WHERE FDEID= F_ID2;
					DELETE FROM FDE_OBJECT_LOCKS WHERE FDEID= F_ID2;	
					DELETE FROM FDE_CONNECTIONINFO WHERE FDEID= F_ID2;
					DELETE FROM FDE_PROCESS_INFORMATION WHERE FDEID= F_ID2;
				END IF;
			UNTIL DONE END REPEAT;
		END IF;
		
	IF NOT BSUCCESS THEN
		ROLLBACK;
	ELSE 
		COMMIT;
	END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

/**删除已经死亡连接进程，删除内容包括死亡连接进程相关的表锁，连接信息，进程信息*/
CREATE  PROCEDURE FDE_PROCESS_DELETE_DEADPROCESS()
BEGIN 
	DECLARE DONE INT DEFAULT 0;
	DECLARE F_ID INT DEFAULT 0;
	DECLARE CUR CURSOR FOR SELECT FDEID FROM FDE_PROCESS_INFORMATION 
		WHERE FDEID NOT IN(SELECT A.FDEID FROM FDE_CONNECTIONINFO A INNER JOIN INFORMATION_SCHEMA.PROCESSLIST B WHERE A.CONNECTID=B.ID);
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	OPEN  CUR;
	REPEAT
	FETCH CUR INTO F_ID;
	IF NOT DONE THEN
		DELETE FROM FDE_TABLE_LOCKS WHERE FDEID= F_ID;
		DELETE FROM FDE_OBJECT_LOCKS WHERE FDEID= F_ID;	
		DELETE FROM FDE_CONNECTIONINFO WHERE FDEID=F_ID;
		DELETE FROM FDE_PROCESS_INFORMATION WHERE FDEID=F_ID;
	END IF;
	UNTIL DONE END REPEAT;
	CLOSE  CUR;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

/**从PROCESSLIST查找该CONNECTIONID是否存在，如果存在就往进行信息表和连接信息表中插入相应的记录*/

CREATE  PROCEDURE FDE_PROCESS_INSERT(
	IN CONNECTIONID INT,
	IN PID INT,
	IN DIRECT_CONNECT CHAR(1),
	OUT F_ID INT)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE BSUCCESS INT DEFAULT 1;
	DECLARE USERNAME VARCHAR(16);
	DECLARE HOSTNAME VARCHAR(64);
	DECLARE CONN_ID INT;
	DECLARE FID INT;
	DECLARE CUR CURSOR FOR SELECT ID,USER,HOST FROM INFORMATION_SCHEMA.PROCESSLIST ;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET BSUCCESS = 0;
	SET F_ID = -1;
	OPEN  CUR;
	REPEAT
	FETCH  CUR INTO CONN_ID, USERNAME,HOSTNAME;
		IF NOT DONE THEN	
			IF CONNECTIONID = CONN_ID THEN
				START TRANSACTION;
				INSERT INTO FDE_PROCESS_INFORMATION (SPID,PID,STARTTIME,OWNER,DIRECTCONNECT) VALUES(CONNECTIONID,PID,NOW(),USERNAME,DIRECT_CONNECT);
				SELECT LAST_INSERT_ID() INTO FID;
				INSERT INTO FDE_CONNECTIONINFO (CONNECTID,HOST,USERNAME,FDEID) VALUES(CONNECTIONID,HOSTNAME,USERNAME,FID);
				IF NOT BSUCCESS THEN
					ROLLBACK;
				ELSE 
					COMMIT;
					SET F_ID = FID;
				END IF;
			SET DONE = 1;
			END IF;
		END IF;
	UNTIL DONE END REPEAT;
	CLOSE  CUR;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

/**检查指定的FDE_ID对应的连接是否还活着，如果还活着返回1，否则该FDE_ID对应的连接死亡，删除相关内容*/
CREATE  PROCEDURE FDE_TABLE_CHECK_LOCK_CONFLICTS(IN F_ID INT,OUT RESULT INT)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE EXIST INT DEFAULT 0;
	DECLARE CONN_ID,CONN_ID1 INT;
	DECLARE HOST_NAME,HOST_NAME1 VARCHAR(64);
	DECLARE USER_NAME,USER_NAME1 VARCHAR(16);
	DECLARE CUR CURSOR FOR SELECT ID,USER,HOST FROM INFORMATION_SCHEMA.PROCESSLIST;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	SELECT CONNECTID,HOST,USERNAME INTO CONN_ID,HOST_NAME,USER_NAME FROM FDE_CONNECTIONINFO WHERE FDEID=F_ID;
	
	SET RESULT = 0;
	OPEN  CUR;
	REPEAT
		FETCH  CUR INTO CONN_ID1,USER_NAME1,HOST_NAME1;
		IF NOT DONE THEN
			IF CONN_ID = CONN_ID1 AND USER_NAME=USER_NAME1 AND HOST_NAME=HOST_NAME1 THEN 
				SET DONE = 1;
				SET EXIST = 1;
				SET RESULT = 1;
			END IF;
		END IF;
	UNTIL DONE END REPEAT;
	CLOSE  CUR;
	
	IF NOT EXIST THEN 
		CALL FDE_PROCESS_DELETE(F_ID, 0);
	SET RESULT = 0;
	END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_TABLE_LOCK(
	IN F_ID INT,
	IN CLASS_ID INT,
	IN LOCKTYPE CHAR(1),
	OUT RET_LOCKTYPE CHAR(1),
	OUT RESULT INT)
BEGIN
	DECLARE LOCKCOUNT INT DEFAULT 0;
	SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_TABLE_LOCKS WHERE CLASSID = CLASS_ID AND FDEID = F_ID;
	IF LOCKCOUNT = 0 THEN
		CALL FDE_TABLE_LOCK_INSERT(F_ID,CLASS_ID,LOCKTYPE,RET_LOCKTYPE,RESULT);
	ELSE
		CALL FDE_TABLE_LOCK_UPDATE(F_ID,CLASS_ID,LOCKTYPE,RESULT);
		SET RET_LOCKTYPE = LOCKTYPE;
	END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_TABLE_LOCK_DELETE(IN FDE_ID INT,IN CLASS_ID INT)
BEGIN
	DELETE FROM FDE_TABLE_LOCKS WHERE CLASSID = CLASS_ID AND FDEID=FDE_ID;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_TABLE_LOCK_DELETE_USER(IN FDE_ID INT)
BEGIN
	DELETE FROM FDE_TABLE_LOCKS WHERE FDEID=FDE_ID;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_TABLE_LOCK_INSERT(
    IN _F_ID INT,
    IN _CLASS_ID INT,
    IN _LOCKTYPE CHAR(1),
    OUT RET_LOCKTYPE CHAR(1),
    OUT RESULT INT)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE BSUCCESS INT DEFAULT 1;
	DECLARE RES INT DEFAULT 0;
	DECLARE LOCKCOUNT INT DEFAULT 0;
	DECLARE E_F_ID INT DEFAULT 0;
	DECLARE HASELOCK INT DEFAULT 0;
	DECLARE CUR CURSOR FOR SELECT DISTINCT FDEID FROM FDE_TABLE_LOCKS WHERE CLASSID = _CLASS_ID ;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_TABLE_LOCKS WHERE CLASSID = _CLASS_ID;
	IF LOCKCOUNT=0 THEN
		INSERT INTO FDE_TABLE_LOCKS(FDEID,CLASSID,LOCKTYPE) VALUES(_F_ID,_CLASS_ID,UPPER(_LOCKTYPE));
		SET RESULT = 0;
		SET RET_LOCKTYPE = UPPER(_LOCKTYPE);
	ELSE
        /**只有在已有的表锁下才执行删除死亡线程，减少不必要的操作*/
		CALL FDE_PROCESS_DELETE_DEADPROCESS();
		SELECT COUNT(*),FDEID INTO LOCKCOUNT,E_F_ID FROM FDE_TABLE_LOCKS WHERE CLASSID =_CLASS_ID AND LOCKTYPE='E' LIMIT 0 , 1;
		IF LOCKCOUNT>0 THEN
			CALL FDE_TABLE_CHECK_LOCK_CONFLICTS(E_F_ID,RES);
			IF RES = 1 THEN 
				SET HASELOCK = 1;
			ELSE 
				SET HASELOCK = 0;
			END IF;
		END IF;
		IF HASELOCK THEN
			SET RESULT = 1;
		ELSE
			IF UPPER(_LOCKTYPE) ='E' THEN
				OPEN  CUR;
				REPEAT
					FETCH  CUR INTO E_F_ID;
					IF NOT DONE THEN
						CALL FDE_TABLE_CHECK_LOCK_CONFLICTS(E_F_ID,RES);
						IF RES = 1 THEN
							SET BSUCCESS = 0;
							SET DONE = 1;
						END IF;
					END IF;
				UNTIL DONE END REPEAT;
				CLOSE  CUR;
				IF NOT BSUCCESS THEN
					SET RESULT = 1;
				ELSE
					INSERT INTO FDE_TABLE_LOCKS(FDEID,CLASSID,LOCKTYPE) VALUES(_F_ID,_CLASS_ID,'E');
					SET RET_LOCKTYPE = 'E';
					SET RESULT = 0;
				END IF;
			ELSE
				SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_TABLE_LOCKS WHERE CLASSID = _CLASS_ID AND LOCKTYPE='S';
				IF LOCKCOUNT = 0 THEN 
					INSERT INTO FDE_TABLE_LOCKS(FDEID,CLASSID,LOCKTYPE) VALUES(_F_ID,_CLASS_ID,'R');
					SET RET_LOCKTYPE = 'R';
				ELSE
					INSERT INTO FDE_TABLE_LOCKS(FDEID,CLASSID,LOCKTYPE) VALUES(_F_ID,_CLASS_ID,'S');
					SET RET_LOCKTYPE = 'S';
				END IF;
				SET RESULT = 0;
			END IF;
		END IF;
    END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE PROCEDURE FDE_TABLE_LOCK_UPDATE(
    IN _F_ID INT,
    IN _CLASS_ID INT,
    IN _LOCKTYPE CHAR(1),
    OUT RESULT INT)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE BSUCCESS INT DEFAULT 1;
	DECLARE RES INT DEFAULT 0;
	DECLARE LOCKCOUNT INT DEFAULT 0;
	DECLARE E_F_ID INT DEFAULT 0;
	DECLARE CUR CURSOR FOR SELECT DISTINCT FDEID FROM FDE_TABLE_LOCKS WHERE CLASSID = _CLASS_ID ;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
	
	CALL FDE_PROCESS_DELETE_DEADPROCESS();
	SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_TABLE_LOCKS WHERE CLASSID = _CLASS_ID AND FDEID=_F_ID;
	IF LOCKCOUNT=0 THEN
		SET RESULT = 1;
	ELSE
		IF UPPER(_LOCKTYPE)='S' THEN
			UPDATE FDE_TABLE_LOCKS SET LOCKTYPE='S' WHERE FDEID=_F_ID AND CLASSID = _CLASS_ID;
			SET RESULT = 0;
		ELSE
			OPEN  CUR;
			REPEAT
				FETCH  CUR INTO E_F_ID;
				IF NOT DONE AND E_F_ID!=_F_ID THEN	
					CALL FDE_TABLE_CHECK_LOCK_CONFLICTS(E_F_ID,RES);
					IF RES = 1 THEN
						SET BSUCCESS = 0;
						SET DONE = 1;
					END IF;
				END IF;
			UNTIL DONE END REPEAT;
			CLOSE  CUR;
			
			IF NOT BSUCCESS THEN
				SET RESULT = 1;
			ELSE
				UPDATE FDE_TABLE_LOCKS SET LOCKTYPE='E' WHERE FDEID=_F_ID AND CLASSID = _CLASS_ID;
				SET RESULT = 0;
			END IF;
		END IF;
	END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_OBJECT_LOCK(
	IN F_ID INT,
	IN CLASS_ID INT,
	IN OBJECT_ID INT,
	OUT RESULT INT)
BEGIN
	DECLARE LOCKCOUNT INT DEFAULT 0;
	SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_OBJECT_LOCKS WHERE CLASSID = CLASS_ID AND OBJECTID= OBJECT_ID;
	IF LOCKCOUNT = 0 THEN
		INSERT INTO FDE_OBJECT_LOCKS(FDEID,CLASSID,OBJECTID) VALUES(F_ID,CLASS_ID,OBJECT_ID);
		SET RESULT = 0;
	ELSE
		SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_OBJECT_LOCKS WHERE CLASSID = CLASS_ID AND OBJECTID= OBJECT_ID AND FDEID = F_ID;
		IF LOCKCOUNT = 0 THEN
			CALL FDE_PROCESS_DELETE_DEADPROCESS();
			SELECT COUNT(*) INTO LOCKCOUNT FROM FDE_OBJECT_LOCKS WHERE CLASSID = CLASS_ID AND OBJECTID= OBJECT_ID;
			IF LOCKCOUNT = 0 THEN
				INSERT INTO FDE_OBJECT_LOCKS(FDEID,CLASSID,OBJECTID) VALUES(F_ID,CLASS_ID,OBJECT_ID);
				SET RESULT = 0;
			ELSE
				SET RESULT = 1;
			END IF;
		ELSE
			SET RESULT = 0;
		END IF;
	END IF;
END$$

DELIMITER ; 
;/*#*/;


DELIMITER $$

CREATE  PROCEDURE FDE_OBJECT_LOCK_DELETE(IN FDE_ID INT,IN CLASS_ID INT,IN OBJECT_ID INT)
BEGIN
	DELETE FROM FDE_OBJECT_LOCKS WHERE CLASSID = CLASS_ID AND OBJECTID=OBJECT_ID AND FDEID=FDE_ID;
END$$

DELIMITER ; 
;/*#*/;